name 'formatron_uchiwa'
version '0.1.1'
description 'Formatron Uchiwa cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/uchiwa-cookbook'
issues_url 'https://github.com/formatron/uchiwa-cookbook/issues'
supports 'ubuntu'
